export const translations = {
    ru: {
        Submit: "Отправить",
        Cancel: "Отмена",
        Save: "Сохранить",
        Remove: "Удалить",
        invalid_email: "Некорректный email",
        required: "Это поле обязательно для заполнения",
        Display: "Дисплей",
        Action: "Действие",
        Theme: "Тема",
        Logic: "Логика",
        Preview: "Предпросмотр",
        Size: "Размер",
        Description: "Описание",
        Label: "Название поля",
        "Label Position": "Позиция названия поля",
        Top: "Сверху",
        Bottom: "Снизу",
        Left: "Слева",
        Right: "Справа",
        Validation: "Валидация",
        "Hide preview": "Скрыть предпросмотр",
        "Show preview": "Показать предпросмотр",
        Content: "Content",
        Columns: "Колонки",
        "Field Set": "Набор полей",
        Panel: "Панель",
        Table: "Таблица",
        Tabs: "Вкладки",
        Well: "Карточка",
        "HTML Element": "HTML Element",
        "Phone Number": "Номер телефона",
        Tags: "Теги",
        "Date / Time": "Дата / Вреия",
        Day: "День",
        Survey: "Опрос",
        "Drag and Drop a form component": "Перетащите сюда элемент формы",
        Placeholder: "Подсказка",
        Prefix: "Префикс",
        "Custom CSS Class": "Кастомные CSS классы",
        Autocomplete: "Автозаполнение",
        Hidden: "Скрыть",
        "Hide Label": "Скрыть название",
        "Show Word Counter": "Показать счетчик слов",
        "Show Character Counter": "Показать счетчик символов",
        "Hide Input": "Скрыть вводимые данные",
        "Initial Focus": "Первоначальный фокус",
        "Allow Spellcheck": "Разрешить проверку орфографии",
        Disabled: "Отключить",
        "The label for this field that will appear next to it.":
            "Название поля, которая появится рядом с ним",
        "Position for the label for this field":
            "Расположение названия этого поля",
        "Table View": "Табличное представление",
        "The description is text that will appear below the input field.":
            "Описание - это текст, который появится под полем ввода.",
        "Modal Edit": "Открыть модальное окно при редактировании",
        "Click to set value": "Нажмите, для редактирования значения",
        "The placeholder text that will appear when this field is empty.":
            "Текст-заполнитель, который будет отображаться, когда это поле будет пустым.",
        "Adds a tooltip to the side of this field.":
            "Добавляет всплывающую подсказку сбоку от этого поля.",
        Widget: "Виджет",
        "The widget is the display UI used to input the value of the field.":
            "Виджет - это пользовательский интерфейс отображения, используемый для ввода значения поля",
        "Display Mask": "Маска поля",
        "Apply Mask On": "Использовать Маску для",
        "Allow Multiple Masks": "Разрешить использование нескольких масок",
        "Tab Index": "Индекс табуляции",
        "Sets the tabindex attribute of this component to override the tab order of the form. See the MSDN documentation on tabindex for more information.":
            "Устанавливает атрибут tabindex этого компонента для переопределения порядка табуляции в форме.",
        "Indicates whether input elements can by default have their values automatically completed by the browser. See the MDN documentation on autocomplete for more information.":
            "Указывает, могут ли значения элементов ввода по умолчанию автоматически заполняться браузером. ",
        Radio: "Компонент Радио",
        "Select Boxes": "Выбор элемента",
        Select: "Поле с выбором",
        Container: "Контейнер",
    },
    en: {
        Submit: "Submit",
        Cancel: "Cancel",
        Save: "Save",
        Remove: "Remove",
        invalid_email: "Invalid email",
        required: "This field is required",
        Display: "Display",
        Action: "Action",
        Theme: "Theme",
        Logic: "Logic",
        Preview: "Preview",
        Size: "Size",
        Description: "Description",
        Label: "Field Label",
        "Label Position": "Label Position",
        Top: "Top",
        Bottom: "Bottom",
        Left: "Left",
        Right: "Right",
        Validation: "Validation",
        "Hide preview": "Hide preview",
        "Show preview": "Show preview",
    },
};
